### PR TITLE
Create Endpoints & Reviews Tab

### PR DESCRIPTION
**Pull request by timmy3000**
screencapture-localhost-5173-api-desc-1-2023-01-17-01_28_35
screencapture-localhost-5173-api-desc-1-2023-01-17-01_34_30

### CODE REVIEW

**Review by pablo-clueless — CHANGES_REQUESTED** [review]
- Remove the `React.FC` type from your components and just make sure the `React` import is present.
- Move the components into the `api` folder.

**Comment by timmy3000** [comment]
Which `api` folder?

**Comment by timmy3000** [comment]
- API Consumption

screencapture-localhost-5173-api-f6ece6c2-26b5-425b-add9-9aef33aeb38b-2023-01-18-11_50_01

**Comment by timmy3000** [comment]
- List Methods
screencapture-localhost-5173-api-f6ece6c2-26b5-425b-add9-9aef33aeb38b-2023-01-19-01_38_04

**Pull request merged**
