### PR TITLE
ZapiV2 Home Refinement

### PR DESCRIPTION
**Pull request by Vinyl-Davyl**
- Updated icons and designs on Blogs and Illustrustations light/dark theme
- hamburger popup closes on click of any button page body updated, login button also retracts to default
- Updated card sizes on pricing section equal and aligned
- View more blogPost Structured on same line
- Fixes on footer alignment and Illustrations

### CODE REVIEW

**Review by taiwoAkindele — CHANGES_REQUESTED** [review]
@Vinyl-Davyl Were you able to build on your end? The build is giving an error here. Also I think @PhilemonBrain mentioned that the hamburger should close when you click on the outside. That is not working.

**Comment by Vinyl-Davyl** [comment]
> @Vinyl-Davyl Were you able to build on your end? The build is giving an error here. Also I think @PhilemonBrain mentioned that the hamburger should close when you click on the outside. That is not working.

No
There's not been any Build on my end at the moment. 
But basically, onclick on the login was suppose to retract like the others and that's general(Fixed Now)
Clicking outside would be something that has to be done generally,  would like into that too with priority. 
Thanks @taiwoAkindele 

>

**Comment by taiwoAkindele** [comment]
> > @Vinyl-Davyl Were you able to build on your end? The build is giving an error here. Also I think @PhilemonBrain mentioned that the hamburger should close when you click on the outside. That is not working.
> 
> No There's not been any build on my end at the moment. But basically, onclick on the login was suppose to retract like the others and that's general(Fixed Now) Clicking outside would be something that has to be done generally, would like into that too with priority. Thanks @taiwoAkindele
> 
> >

Please run yarn build and let's know if it builds

**Review by pablo-clueless — CHANGES_REQUESTED** [review]
Please check for console errors and fix them. And also your PR is causing the app to crash, please build it to see the source error and fix it.

**Comment by Vinyl-Davyl** [comment]
> Please check for console errors and fix them. And also your PR is causing the app to crash, please build it to see the source error and fix it.

👍

**Comment by Vinyl-Davyl** [comment]
> > > @Vinyl-Davyl Were you able to build on your end? The build is giving an error here. Also I think @PhilemonBrain mentioned that the hamburger should close when you click on the outside. That is not working.
> > 
> > 
> > No There's not been any build on my end at the moment. But basically, onclick on the login was suppose to retract like the others and that's general(Fixed Now) Clicking outside would be something that has to be done generally, would like into that too with priority. Thanks @taiwoAkindele
> > >
> 
> Please run yarn build and let's know if it builds

Build Successful, Good to go

**Comment by Vinyl-Davyl** [comment]
> Please check for console errors and fix them. And also your PR is causing the app to crash, please build it to see the source error and fix it.

Cleared all console errors, Build Successful, Good to go

**Review by taiwoAkindele — APPROVED** [review]

**Pull request merged**
