### PR TITLE
Discover

### PR DESCRIPTION
**Pull request by taiwoAkindele**
aimodels 1
dark aimodel1

### CODE REVIEW

**Comment by taiwoAkindele** [comment]
aimodels 2
dark aimodel2

**Comment by taiwoAkindele** [comment]
features
darkFeatures

**Comment by taiwoAkindele** [comment]
darkDiscover
discover

**Review by Vinyl-Davyl — APPROVED** [review]
Conflicts with a file

**Comment by taiwoAkindele** [comment]
> Conflicts with a file

fixed

**Pull request merged**
